services:
  - type: web
    name: campaign-inventory-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn simple_dashboard:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DATABASE_URL
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: FLASK_ENV
        value: production
